#
# Run repoman via travis
# See https://github.com/mrueg/repoman-travis
#
language: python

# shard repoman call by arch. Generated as:
# $    cat $(portageq get_repo_path / gentoo)/profiles/arch.list | egrep -v '^#|^$' | while read arch; do echo "    - TOOL=repoman REPOMAN_FLAGS='--include-arches=${arch}'"; done
env:
    - TOOL=pkgcheck
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=alpha'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=amd64'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=arm'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=arm64'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=hppa'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=ia64'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=m68k'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=mips'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=ppc'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=ppc64'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=riscv'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=s390'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=sh'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=sparc'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x86'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=ppc-aix'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=amd64-linux'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=arm-linux'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=arm64-linux'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=ppc64-linux'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x86-linux'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=ppc-macos'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x86-macos'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x64-macos'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=m68k-mint'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=sparc-solaris'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=sparc64-solaris'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x64-solaris'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x86-solaris'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x86-winnt'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x64-cygwin'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x86-cygwin'
before_install:
    - pip install lxml pyyaml
    - pip install pkgcheck
before_script:
    - PORTAGE_VER='2.3.76'
    - sudo chmod a+rwX /etc/passwd /etc/group /etc /var /var/cache
    - mkdir -p travis-overlay /etc/portage /var/cache/distfiles /var/db/repos/gentoo
    - mv !(travis-overlay) travis-overlay/
    - mv .git travis-overlay/
    - wget "https://raw.githubusercontent.com/mrueg/repoman-travis/master/.travis.yml" -O .travis.yml.upstream
    - wget "https://raw.githubusercontent.com/mrueg/repoman-travis/master/spinner.sh"
    - wget -qO - "https://github.com/gentoo/portage/archive/portage-${PORTAGE_VER}.tar.gz" | tar xz
    - wget -qO - "https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz" | tar xz -C /var/db/repos/gentoo --strip-components=1
    - chmod a+rwx spinner.sh
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - wget "https://www.gentoo.org/dtd/metadata.dtd" -O /var/cache/distfiles/metadata.dtd
    - ln -s $TRAVIS_BUILD_DIR/portage-portage-${PORTAGE_VER}/cnf/repos.conf /etc/portage/repos.conf
    - ln -s /var/db/repos/gentoo/profiles/default/linux/amd64/17.0 /etc/portage/make.profile
    - cd travis-overlay
script:
    - if test "${TOOL}" = pkgcheck; then ./../spinner.sh "pkgcheck scan -r ."; else true; fi
    - if test "${TOOL}" = repoman;  then ./../spinner.sh "python ../portage-portage-${PORTAGE_VER}/repoman/bin/repoman full ${REPOMAN_FLAGS}"; else true; fi
