#
# Run repoman via travis
# See https://github.com/mrueg/repoman-travis
#
language: python

# shard repoman call by arch. Generated as:
# $    cat $(portageq get_repo_path / gentoo)/profiles/arch.list | egrep -v '^#|^$' | while read arch; do echo "    - TOOL=repoman REPOMAN_FLAGS='--include-arches=${arch}'"; done
env:
    - TOOL=pkgcheck
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=alpha'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=amd64'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=arm'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=arm64'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=hppa'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=ia64'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=m68k'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=mips'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=ppc'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=ppc64'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=riscv'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=s390'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=sh'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=sparc'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x86'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=ppc-aix'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=amd64-linux'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=arm-linux'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=arm64-linux'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=ppc64-linux'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x86-linux'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=ppc-macos'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x86-macos'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x64-macos'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=m68k-mint'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=sparc-solaris'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=sparc64-solaris'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x64-solaris'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x86-solaris'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x86-winnt'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x64-cygwin'
    - TOOL=repoman REPOMAN_FLAGS='--include-arches=x86-cygwin'
before_install:
    - pip install lxml pyyaml
    - pip install pkgcheck
before_script:
    - THIS_REPO=haskell
    - PORTAGE_VER='2.3.79'
    - SPINNER=/tmp/spinner.sh
    - PORTAGE_DIR="/tmp/portage-portage-${PORTAGE_VER}"
    - echo "Setting up basic directories:"
    - sudo chmod a+rwX /etc/passwd /etc/group /etc /var /var/cache
    - mkdir -p /etc/portage/repos.conf /var/cache/distfiles /var/db/repos/gentoo
    - printf "[${THIS_REPO}]\nlocation = $TRAVIS_BUILD_DIR" > /etc/portage/repos.conf/haskell
    - echo "Installing portage:"
    - wget -qO - "https://github.com/gentoo/portage/archive/portage-${PORTAGE_VER}.tar.gz" | tar xz -C /tmp
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - printf "[gentoo]\nlocation = /var/db/repos/gentoo" > /etc/portage/repos.conf/gentoo
    - printf "[DEFAULT]\nmain-repo = gentoo" > /etc/portage/repos.conf/default
    - echo "Unpacking ::gentoo:"
    - wget -qO - "https://github.com/gentoo-mirror/gentoo/archive/master.tar.gz" | tar xz -C /var/db/repos/gentoo --strip-components=1
    - ln -s /var/db/repos/gentoo/profiles/default/linux/amd64/17.0 /etc/portage/make.profile
    - wget "https://www.gentoo.org/dtd/metadata.dtd" -O /var/cache/distfiles/metadata.dtd
    - echo "Grabbing fidget spinner:"
    - wget "https://raw.githubusercontent.com/mrueg/repoman-travis/master/spinner.sh" -O "${SPINNER}"
    - chmod a+rwx "${SPINNER}"
    - echo "Generating metadata cache:"
    - '"${SPINNER}" "${PORTAGE_DIR}/bin/egencache --repo=${THIS_REPO} --update --jobs=$(nproc)"'
    - "${PORTAGE_DIR}/bin/emerge --info"
script:
    - if test "${TOOL}" = pkgcheck; then "${SPINNER}" "pkgcheck scan --repo=${THIS_REPO} --jobs=$(nproc)"; else true; fi
    - if test "${TOOL}" = repoman;  then "${SPINNER}" "${PORTAGE_DIR}/repoman/bin/repoman full ${REPOMAN_FLAGS}"; else true; fi
